/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateStartStopPlaceArgs } from "./CreateStartStopPlaceArgs";
import { UpdateStartStopPlaceArgs } from "./UpdateStartStopPlaceArgs";
import { DeleteStartStopPlaceArgs } from "./DeleteStartStopPlaceArgs";
import { StartStopPlaceFindManyArgs } from "./StartStopPlaceFindManyArgs";
import { StartStopPlaceFindUniqueArgs } from "./StartStopPlaceFindUniqueArgs";
import { StartStopPlace } from "./StartStopPlace";
import { City } from "../../city/base/City";
import { StartStopPlaceService } from "../startStopPlace.service";

@graphql.Resolver(() => StartStopPlace)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class StartStopPlaceResolverBase {
  constructor(
    protected readonly service: StartStopPlaceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "StartStopPlace",
    action: "read",
    possession: "any",
  })
  async _startStopPlacesMeta(
    @graphql.Args() args: StartStopPlaceFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [StartStopPlace])
  @nestAccessControl.UseRoles({
    resource: "StartStopPlace",
    action: "read",
    possession: "any",
  })
  async startStopPlaces(
    @graphql.Args() args: StartStopPlaceFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<StartStopPlace[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "StartStopPlace",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => StartStopPlace, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "StartStopPlace",
    action: "read",
    possession: "own",
  })
  async startStopPlace(
    @graphql.Args() args: StartStopPlaceFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<StartStopPlace | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "StartStopPlace",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => StartStopPlace)
  @nestAccessControl.UseRoles({
    resource: "StartStopPlace",
    action: "create",
    possession: "any",
  })
  async createStartStopPlace(
    @graphql.Args() args: CreateStartStopPlaceArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<StartStopPlace> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "StartStopPlace",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"StartStopPlace"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        city: args.data.city
          ? {
              connect: args.data.city,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => StartStopPlace)
  @nestAccessControl.UseRoles({
    resource: "StartStopPlace",
    action: "update",
    possession: "any",
  })
  async updateStartStopPlace(
    @graphql.Args() args: UpdateStartStopPlaceArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<StartStopPlace | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "StartStopPlace",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"StartStopPlace"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          city: args.data.city
            ? {
                connect: args.data.city,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => StartStopPlace)
  @nestAccessControl.UseRoles({
    resource: "StartStopPlace",
    action: "delete",
    possession: "any",
  })
  async deleteStartStopPlace(
    @graphql.Args() args: DeleteStartStopPlaceArgs
  ): Promise<StartStopPlace | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => City, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "StartStopPlace",
    action: "read",
    possession: "any",
  })
  async city(
    @graphql.Parent() parent: StartStopPlace,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<City | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "City",
    });
    const result = await this.service.getCity(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
