/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateFoodPlaceArgs } from "./CreateFoodPlaceArgs";
import { UpdateFoodPlaceArgs } from "./UpdateFoodPlaceArgs";
import { DeleteFoodPlaceArgs } from "./DeleteFoodPlaceArgs";
import { FoodPlaceFindManyArgs } from "./FoodPlaceFindManyArgs";
import { FoodPlaceFindUniqueArgs } from "./FoodPlaceFindUniqueArgs";
import { FoodPlace } from "./FoodPlace";
import { City } from "../../city/base/City";
import { FoodPlaceService } from "../foodPlace.service";

@graphql.Resolver(() => FoodPlace)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class FoodPlaceResolverBase {
  constructor(
    protected readonly service: FoodPlaceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "FoodPlace",
    action: "read",
    possession: "any",
  })
  async _foodPlacesMeta(
    @graphql.Args() args: FoodPlaceFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [FoodPlace])
  @nestAccessControl.UseRoles({
    resource: "FoodPlace",
    action: "read",
    possession: "any",
  })
  async foodPlaces(
    @graphql.Args() args: FoodPlaceFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FoodPlace[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "FoodPlace",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => FoodPlace, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "FoodPlace",
    action: "read",
    possession: "own",
  })
  async foodPlace(
    @graphql.Args() args: FoodPlaceFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FoodPlace | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "FoodPlace",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => FoodPlace)
  @nestAccessControl.UseRoles({
    resource: "FoodPlace",
    action: "create",
    possession: "any",
  })
  async createFoodPlace(
    @graphql.Args() args: CreateFoodPlaceArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FoodPlace> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "FoodPlace",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"FoodPlace"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        city: args.data.city
          ? {
              connect: args.data.city,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => FoodPlace)
  @nestAccessControl.UseRoles({
    resource: "FoodPlace",
    action: "update",
    possession: "any",
  })
  async updateFoodPlace(
    @graphql.Args() args: UpdateFoodPlaceArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FoodPlace | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "FoodPlace",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"FoodPlace"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          city: args.data.city
            ? {
                connect: args.data.city,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => FoodPlace)
  @nestAccessControl.UseRoles({
    resource: "FoodPlace",
    action: "delete",
    possession: "any",
  })
  async deleteFoodPlace(
    @graphql.Args() args: DeleteFoodPlaceArgs
  ): Promise<FoodPlace | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => City, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "FoodPlace",
    action: "read",
    possession: "any",
  })
  async city(
    @graphql.Parent() parent: FoodPlace,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<City | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "City",
    });
    const result = await this.service.getCity(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
