/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { FoodPlaceCreateNestedManyWithoutCitiesInput } from "./FoodPlaceCreateNestedManyWithoutCitiesInput";
import { Type } from "class-transformer";
import { StartStopPlaceCreateNestedManyWithoutCitiesInput } from "./StartStopPlaceCreateNestedManyWithoutCitiesInput";
@InputType()
class CityCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  code?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  country?: string | null;

  @ApiProperty({
    required: false,
    type: () => FoodPlaceCreateNestedManyWithoutCitiesInput,
  })
  @ValidateNested()
  @Type(() => FoodPlaceCreateNestedManyWithoutCitiesInput)
  @IsOptional()
  @Field(() => FoodPlaceCreateNestedManyWithoutCitiesInput, {
    nullable: true,
  })
  foodPlaces?: FoodPlaceCreateNestedManyWithoutCitiesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => StartStopPlaceCreateNestedManyWithoutCitiesInput,
  })
  @ValidateNested()
  @Type(() => StartStopPlaceCreateNestedManyWithoutCitiesInput)
  @IsOptional()
  @Field(() => StartStopPlaceCreateNestedManyWithoutCitiesInput, {
    nullable: true,
  })
  startStopPlaces?: StartStopPlaceCreateNestedManyWithoutCitiesInput;
}
export { CityCreateInput };
