/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AttractionUpdateManyWithoutCitiesInput } from "./AttractionUpdateManyWithoutCitiesInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { FoodPlaceUpdateManyWithoutCitiesInput } from "./FoodPlaceUpdateManyWithoutCitiesInput";
import { StartStopPlaceUpdateManyWithoutCitiesInput } from "./StartStopPlaceUpdateManyWithoutCitiesInput";
@InputType()
class CityUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AttractionUpdateManyWithoutCitiesInput,
  })
  @ValidateNested()
  @Type(() => AttractionUpdateManyWithoutCitiesInput)
  @IsOptional()
  @Field(() => AttractionUpdateManyWithoutCitiesInput, {
    nullable: true,
  })
  attractions?: AttractionUpdateManyWithoutCitiesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  code?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  country?: string | null;

  @ApiProperty({
    required: false,
    type: () => FoodPlaceUpdateManyWithoutCitiesInput,
  })
  @ValidateNested()
  @Type(() => FoodPlaceUpdateManyWithoutCitiesInput)
  @IsOptional()
  @Field(() => FoodPlaceUpdateManyWithoutCitiesInput, {
    nullable: true,
  })
  foodPlaces?: FoodPlaceUpdateManyWithoutCitiesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => StartStopPlaceUpdateManyWithoutCitiesInput,
  })
  @ValidateNested()
  @Type(() => StartStopPlaceUpdateManyWithoutCitiesInput)
  @IsOptional()
  @Field(() => StartStopPlaceUpdateManyWithoutCitiesInput, {
    nullable: true,
  })
  startStopPlaces?: StartStopPlaceUpdateManyWithoutCitiesInput;
}
export { CityUpdateInput };
