/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateAttractionArgs } from "./CreateAttractionArgs";
import { UpdateAttractionArgs } from "./UpdateAttractionArgs";
import { DeleteAttractionArgs } from "./DeleteAttractionArgs";
import { AttractionFindManyArgs } from "./AttractionFindManyArgs";
import { AttractionFindUniqueArgs } from "./AttractionFindUniqueArgs";
import { Attraction } from "./Attraction";
import { City } from "../../city/base/City";
import { AttractionService } from "../attraction.service";

@graphql.Resolver(() => Attraction)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class AttractionResolverBase {
  constructor(
    protected readonly service: AttractionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Attraction",
    action: "read",
    possession: "any",
  })
  async _attractionsMeta(
    @graphql.Args() args: AttractionFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Attraction])
  @nestAccessControl.UseRoles({
    resource: "Attraction",
    action: "read",
    possession: "any",
  })
  async attractions(
    @graphql.Args() args: AttractionFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Attraction[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Attraction",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Attraction, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Attraction",
    action: "read",
    possession: "own",
  })
  async attraction(
    @graphql.Args() args: AttractionFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Attraction | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Attraction",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Attraction)
  @nestAccessControl.UseRoles({
    resource: "Attraction",
    action: "create",
    possession: "any",
  })
  async createAttraction(
    @graphql.Args() args: CreateAttractionArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Attraction> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Attraction",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Attraction"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        city: args.data.city
          ? {
              connect: args.data.city,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Attraction)
  @nestAccessControl.UseRoles({
    resource: "Attraction",
    action: "update",
    possession: "any",
  })
  async updateAttraction(
    @graphql.Args() args: UpdateAttractionArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Attraction | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Attraction",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Attraction"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          city: args.data.city
            ? {
                connect: args.data.city,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Attraction)
  @nestAccessControl.UseRoles({
    resource: "Attraction",
    action: "delete",
    possession: "any",
  })
  async deleteAttraction(
    @graphql.Args() args: DeleteAttractionArgs
  ): Promise<Attraction | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => City, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Attraction",
    action: "read",
    possession: "any",
  })
  async city(
    @graphql.Parent() parent: Attraction,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<City | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "City",
    });
    const result = await this.service.getCity(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
